### PR TITLE
Test case: invalid packit.yaml

### PR DESCRIPTION
**Pull request by dhodovsk**
Test case for: https://github.com/packit-service/packit-service/issues/70

### CODE REVIEW

**Comment by dhodovsk** [comment]
Damn, it seems it is not handled nicely - https://sentry.io/organizations/red-hat-0p/issues/1458792767

**Comment by lachmanfrantisek** [comment]
@lbarcziova this test-case is important -- please, create a new one. (If you already don't have a plan to do it.

(What about having use-case description, how-to-test and expected behaviour described in the PR description?)

**Comment by lbarcziova** [comment]
@lachmanfrantisek Yes, I am planning to recreate them

**Pull request closed without merging**
